[package]
name = "multimpaste"
version = "0.1.0"
edition = "2024"

[dependencies]
arboard = "3.6.1"
auto-launch = "0.6.0"
dirs = "7.0.0"
eframe = "0.36.2"
enigo = "0.6.1"
global-hotkey = "0.8.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tray-icon = "0.25.0"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.4"
objc2-app-kit = { version = "0.3.2", default-features = false, features = ["std", "NSApplication", "NSResponder", "NSPasteboard", "NSGraphics"] }
objc2-foundation = { version = "0.3.2", default-features = false, features = ["std", "NSString", "NSObject", "NSProcessInfo"] }
